-- Clinic Karma canonical PostgreSQL schema.
-- Use `npm run db:migrate` for an existing database. This file documents the
-- complete schema and can be applied to a new, empty PostgreSQL database.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS schema_migrations (
  version varchar(40) PRIMARY KEY,
  name text NOT NULL,
  checksum char(64) NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "User" (
  user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  nic varchar(20),
  email varchar(254),
  contact_number varchar(20),
  address varchar(255),
  username varchar(50) NOT NULL,
  password_hash varchar(255) NOT NULL,
  user_type varchar(30) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_role_check CHECK (
    user_type IN (
      'patient', 'doctor', 'receptionist', 'lab-coordinator',
      'branch-manager', 'top-manager'
    )
  )
);

CREATE UNIQUE INDEX user_username_unique_ci ON "User" (lower(username));
CREATE UNIQUE INDEX user_nic_unique ON "User" (nic) WHERE nic IS NOT NULL;
CREATE UNIQUE INDEX user_email_unique_ci ON "User" (lower(email)) WHERE email IS NOT NULL;

CREATE TABLE "Branch" (
  "Branch_Name" varchar(50) PRIMARY KEY,
  "Contact_Number" varchar(20),
  "Address" varchar(255) NOT NULL,
  "Is_Active" boolean NOT NULL DEFAULT true,
  "Created_At" timestamptz NOT NULL DEFAULT now(),
  "Updated_At" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "Staff" (
  "Staff_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "User_ID" integer NOT NULL UNIQUE REFERENCES "User"(user_id) ON DELETE RESTRICT,
  "Branch_Name" varchar(50) REFERENCES "Branch"("Branch_Name") ON DELETE RESTRICT,
  "Salary" numeric(12,2) NOT NULL DEFAULT 0 CHECK ("Salary" >= 0),
  "Is_Active" boolean NOT NULL DEFAULT true,
  "Created_At" timestamptz NOT NULL DEFAULT now(),
  "Updated_At" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "Patient" (
  patient_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL UNIQUE REFERENCES "User"(user_id) ON DELETE RESTRICT,
  date_of_birth date,
  gender varchar(30),
  emergency_contact varchar(20),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT patient_dob_check CHECK (date_of_birth IS NULL OR date_of_birth <= CURRENT_DATE)
);

CREATE TABLE "Doctor" (
  "Doctor_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Staff_ID" integer NOT NULL UNIQUE REFERENCES "Staff"("Staff_ID") ON DELETE RESTRICT
);

CREATE TABLE "Specialization" (
  "Specialization_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Specialization_Name" varchar(100) NOT NULL UNIQUE,
  "Consultation_Fee" numeric(12,2) NOT NULL DEFAULT 0 CHECK ("Consultation_Fee" >= 0)
);

CREATE TABLE "Doctor_Specialization" (
  "Doctor_ID" integer NOT NULL REFERENCES "Doctor"("Doctor_ID") ON DELETE CASCADE,
  "Specialization_ID" integer NOT NULL REFERENCES "Specialization"("Specialization_ID") ON DELETE RESTRICT,
  PRIMARY KEY ("Doctor_ID", "Specialization_ID")
);

CREATE TABLE "Appointment" (
  "Appointment_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Patient_ID" integer NOT NULL REFERENCES "Patient"(patient_id) ON DELETE RESTRICT,
  "Appointment_Date" date NOT NULL,
  "Status" varchar(20) NOT NULL DEFAULT 'Scheduled',
  "Type" varchar(20) NOT NULL,
  "Branch_Name" varchar(50) NOT NULL REFERENCES "Branch"("Branch_Name") ON DELETE RESTRICT,
  "Created_At" timestamptz NOT NULL DEFAULT now(),
  "Updated_At" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT appointment_status_check CHECK ("Status" IN ('Scheduled', 'Confirmed', 'Completed', 'Cancelled')),
  CONSTRAINT appointment_type_check CHECK ("Type" IN ('Consultation', 'Laboratory'))
);

CREATE TABLE "Doctor_Appointment" (
  "Appointment_ID" integer PRIMARY KEY REFERENCES "Appointment"("Appointment_ID") ON DELETE CASCADE,
  "Doctor_ID" integer NOT NULL REFERENCES "Doctor"("Doctor_ID") ON DELETE RESTRICT,
  "Start_Time" time NOT NULL,
  "Is_Emergency" boolean NOT NULL DEFAULT false,
  "Diagnosis" text,
  "Prescription" text,
  "Additional_Notes" text,
  "Specialization_ID" integer NOT NULL REFERENCES "Specialization"("Specialization_ID") ON DELETE RESTRICT
);

CREATE TABLE "Catalogue" (
  "Catalogue_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Treatment_name" varchar(100) NOT NULL UNIQUE,
  "Price" numeric(12,2) NOT NULL CHECK ("Price" >= 0),
  "Is_Active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "Treatment_Appointment" (
  "Appointment_ID" integer PRIMARY KEY REFERENCES "Appointment"("Appointment_ID") ON DELETE CASCADE,
  "Catalogue_ID" integer NOT NULL REFERENCES "Catalogue"("Catalogue_ID") ON DELETE RESTRICT,
  "Report_Links" text,
  "Uploaded_At" timestamptz
);

CREATE TABLE "Insurance" (
  "Insurance_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Provider_Name" varchar(100) NOT NULL UNIQUE,
  "Coverage_Percentage" numeric(5,2) NOT NULL CHECK ("Coverage_Percentage" BETWEEN 0 AND 100),
  "Type" varchar(30) NOT NULL,
  "Is_Active" boolean NOT NULL DEFAULT true,
  "Created_At" timestamptz NOT NULL DEFAULT now(),
  "Updated_At" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "Patient_Insurance" (
  "Patient_Insurance_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Patient_ID" integer NOT NULL REFERENCES "Patient"(patient_id) ON DELETE RESTRICT,
  "Insurance_ID" integer NOT NULL REFERENCES "Insurance"("Insurance_ID") ON DELETE RESTRICT,
  "Policy_Number" varchar(50) NOT NULL,
  "Status" varchar(20) NOT NULL DEFAULT 'Pending',
  "Created_At" timestamptz NOT NULL DEFAULT now(),
  "Updated_At" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT patient_insurance_status_check CHECK ("Status" IN ('Pending', 'Approved', 'Rejected')),
  CONSTRAINT patient_insurance_policy_unique UNIQUE ("Patient_ID", "Insurance_ID", "Policy_Number")
);

CREATE TABLE "Billing" (
  "Bill_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Appointment_ID" integer NOT NULL UNIQUE REFERENCES "Appointment"("Appointment_ID") ON DELETE RESTRICT,
  "Total_Amount" numeric(12,2) NOT NULL DEFAULT 0,
  "Insured_Amount" numeric(12,2) NOT NULL DEFAULT 0,
  "Patient_Amount" numeric(12,2) NOT NULL DEFAULT 0,
  "Due_Date" date NOT NULL,
  "Insurance_ID" integer REFERENCES "Insurance"("Insurance_ID") ON DELETE RESTRICT,
  "Status" varchar(20) NOT NULL DEFAULT 'Pending',
  "Created_At" timestamptz NOT NULL DEFAULT now(),
  "Updated_At" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT billing_amounts_check CHECK (
    "Total_Amount" >= 0 AND "Insured_Amount" >= 0 AND "Patient_Amount" >= 0
    AND "Total_Amount" = "Insured_Amount" + "Patient_Amount"
  ),
  CONSTRAINT billing_status_check CHECK ("Status" IN ('Pending', 'Partial', 'Paid'))
);

CREATE TABLE "Payment" (
  "Payment_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Bill_ID" integer NOT NULL REFERENCES "Billing"("Bill_ID") ON DELETE RESTRICT,
  "Amount" numeric(12,2) NOT NULL CHECK ("Amount" > 0),
  "Date_Time" timestamptz NOT NULL DEFAULT now(),
  "Payment_Method" varchar(50) NOT NULL,
  "Reference" varchar(100)
);

CREATE TABLE "Insurance_Claim" (
  "Insurance_Claim_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Bill_ID" integer NOT NULL REFERENCES "Billing"("Bill_ID") ON DELETE RESTRICT,
  "Patient_Insurance_ID" integer NOT NULL REFERENCES "Patient_Insurance"("Patient_Insurance_ID") ON DELETE RESTRICT,
  "Insurance_ID" integer NOT NULL REFERENCES "Insurance"("Insurance_ID") ON DELETE RESTRICT,
  "Claim_Amount" numeric(12,2) NOT NULL CHECK ("Claim_Amount" > 0),
  "Claim_Status" varchar(20) NOT NULL DEFAULT 'Pending',
  "Submitted_Date" date NOT NULL DEFAULT CURRENT_DATE,
  "Decision_Date" date,
  CONSTRAINT insurance_claim_status_check CHECK ("Claim_Status" IN ('Pending', 'Approved', 'Rejected')),
  CONSTRAINT insurance_claim_decision_check CHECK ("Decision_Date" IS NULL OR "Decision_Date" >= "Submitted_Date")
);

CREATE TABLE refresh_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES "User"(user_id) ON DELETE CASCADE,
  jti uuid NOT NULL UNIQUE,
  token_hash char(64) NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  revoked boolean NOT NULL DEFAULT false,
  CONSTRAINT refresh_token_expiry_check CHECK (expires_at > created_at)
);

CREATE TABLE audit_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  table_name text NOT NULL,
  record_id text NOT NULL,
  operation_type text NOT NULL CHECK (operation_type IN ('INSERT', 'UPDATE', 'DELETE')),
  changed_at timestamptz NOT NULL DEFAULT now(),
  changed_by_user_id integer REFERENCES "User"(user_id) ON DELETE SET NULL,
  original_values jsonb,
  new_values jsonb
);

CREATE INDEX appointment_patient_date_idx ON "Appointment" ("Patient_ID", "Appointment_Date");
CREATE INDEX appointment_branch_date_idx ON "Appointment" ("Branch_Name", "Appointment_Date");
CREATE INDEX doctor_appointment_slot_idx ON "Doctor_Appointment" ("Doctor_ID", "Start_Time");
CREATE INDEX payment_bill_date_idx ON "Payment" ("Bill_ID", "Date_Time");
CREATE INDEX refresh_tokens_user_idx ON refresh_tokens (user_id);
CREATE INDEX refresh_tokens_expiry_idx ON refresh_tokens (expires_at) WHERE revoked = false;
CREATE INDEX audit_log_record_idx ON audit_log (table_name, record_id, changed_at DESC);

CREATE OR REPLACE VIEW appointment_details AS
SELECT
  a."Appointment_ID",
  a."Appointment_Date",
  a."Status",
  a."Type",
  a."Branch_Name",
  patient_user.name AS patient_name,
  patient_user.username AS patient_username,
  doctor_user.name AS doctor_name,
  da."Start_Time",
  da."Is_Emergency",
  specialization."Specialization_Name"
FROM "Appointment" a
JOIN "Patient" patient ON patient.patient_id = a."Patient_ID"
JOIN "User" patient_user ON patient_user.user_id = patient.user_id
LEFT JOIN "Doctor_Appointment" da ON da."Appointment_ID" = a."Appointment_ID"
LEFT JOIN "Doctor" doctor ON doctor."Doctor_ID" = da."Doctor_ID"
LEFT JOIN "Staff" staff ON staff."Staff_ID" = doctor."Staff_ID"
LEFT JOIN "User" doctor_user ON doctor_user.user_id = staff."User_ID"
LEFT JOIN "Specialization" specialization ON specialization."Specialization_ID" = da."Specialization_ID";

CREATE OR REPLACE VIEW billing_summary AS
SELECT
  b."Bill_ID",
  b."Appointment_ID",
  b."Total_Amount",
  b."Insured_Amount",
  b."Patient_Amount",
  b."Status",
  b."Due_Date",
  COALESCE(SUM(p."Amount"), 0)::numeric(12,2) AS total_paid,
  GREATEST(b."Patient_Amount" - COALESCE(SUM(p."Amount"), 0), 0)::numeric(12,2) AS remaining_amount
FROM "Billing" b
LEFT JOIN "Payment" p ON p."Bill_ID" = b."Bill_ID"
GROUP BY b."Bill_ID";
